### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by aquynh** [lunixbochs/patchkit#1]
looks like an exciting project! linked to your tool from our website now: http://www.keystone-engine.org/showcase/

keep it up, cheers!

**Comment by aquynh** [comment]
another great work from you! any plan to support PE files?

**Comment by lunixbochs** [comment]
Thanks! Yes, I plan to work on new binary backends for ELF (elffile.py is fragile), MachO, and PE.

**Comment by lunixbochs** [comment]
closing in favor of #8
