### ISSUE TITLE
why。 NameError: name 'KS_ARCH_X86' is not defined？

### ISSUE THREAD

**Issue by letitbezh** [lunixbochs/patchkit#18]
File "./patch", line 6, in <module>
    from core import Patcher
  File "/home/angr/patchkit-master/core/__init__.py", line 1, in <module>
    from patcher import Patcher
  File "/home/angr/patchkit-master/core/patcher.py", line 7, in <module>
    from binary import Binary
  File "/home/angr/patchkit-master/core/binary.py", line 8, in <module>
    from context import Context
  File "/home/angr/patchkit-master/core/context.py", line 4, in <module>
    import arch
  File "/home/angr/patchkit-master/core/arch.py", line 39, in <module>
    class x86(Arch):
  File "/home/angr/patchkit-master/core/arch.py", line 41, in x86
    _ks = KS_ARCH_X86, KS_MODE_32
NameError: name 'KS_ARCH_X86' is not defined

what should I do？

**Comment by lunixbochs** [comment]
Did you install keystone with pip? This indicates your keystone bindings are broken.

**Comment by letitbezh** [comment]
when I python import keystone. there is nothing happened..  if because  I. don't  install ida ?   and I think your example is not very clear.   thank you for your response.

**Comment by lunixbochs** [comment]
I've seen the issue before, your keystone bindings don't include constants, or weren't built including x86. An `import keystone` will work, but `import keystone; dir(keystone)` will be very short and not include things like `KS_ARCH_X86`. How did you install keystone?

**Comment by letitbezh** [comment]
yeah... i test it ,you are right.   firstly, I choose install through yours ./deps.sh , but it wrong ,then I install cmake. then I use ./deps.sh...  reinstall it is useful?

**Comment by lunixbochs** [comment]
I haven't tried deps.sh in a while, so it could be broken. What's your OS? I'll try.

**Comment by letitbezh** [comment]
ubuntu 14.04., now I reinstall it., only for test.

**Comment by lunixbochs** [comment]
I just ran `./deps.sh` on Ubuntu 16.04 without problems.

**Comment by letitbezh** [comment]
thank you at all。。。 it is because cmake 。。
