### ISSUE TITLE
replacing a C function doesn't work

### ISSUE THREAD

**Issue by Ver0n1ca** [lunixbochs/patchkit#29]
Hi, I used this tool to hook a jle instruction in a binary. But the instrumented function doesn't work. The c code of the binary is as follows:
```c
#include<stdio.h>
int main(){
	int n;
	scanf("%d",&n);
	if(n>10){
		printf("Yes");
	}
	else
		printf("No");
}
```
my patch file:
```python
def replace_jmp(pt):
    # pretend jmp is at this address:
    old_jmp =  0x400629

    # inject a function to replace jmp()
    addr = pt.inject(c=r'''
    void jmp_stub() {
        printf("stubbed jmp\n");
        return;
    }
    ''')

    # hook the entry point to make it call addr (ret will run the original entry point)
    pt.hook(old_jmp, addr)
```
the addr of the binary:
```
 0x400623 	 mov	 eax, dword ptr [rbp - 0xc]
 0x400626 	 cmp	 eax, 0xa //cmp input with 10
 0x400629 	 jle	 0x40063c 
 0x40062b 	 mov	 edi, 0x4006f7
 0x400630 	 mov	 eax, 0
```
The output of patch:
```
[*] test_patch.py
 [+] replace_jmp()
  [LINK] printf
  [LINK] puts
  [LINK] strlen
  [INJECT] @0x1e01000-0x1e0100c
  [LINK] transmit
  [INJECT] @0x1e0100c-0x1e01022
  [INJECT] @0x1e01022-0x1e0103b
  [LINK] strupr
  [LINK] toupper
  [LINK] islower
  [INJECT] @0x1e0103b-0x1e01047
  [INJECT] @0x1e01047-0x1e0105b
  [INJECT] @0x1e0105b-0x1e01076
  [LINK] putc
  [INJECT] @0x1e01076-0x1e01099
  [LINK] itoa (includes [atoi, itoa])
  [INJECT] @0x1e01099-0x1e01119
  [INJECT] @0x1e01119-0x1e0139f
  [INJECT] @0x801000-0x80101b
  [INJECT] @0x801033-0x80105a
  [INJECT] @0x80105a-0x80107c
  [PATCH] @0x80101b-0x801027 | "hook stage 1"
  [PATCH] @0x801027-0x801033 | "hook stage 2"
  [PATCH] @0x400629-0x400635 | "hook entry point"
```
No error in it. But when i run the patch binary, the "stubbed jmp" wasn't print out.
I use gdb to debug the patched binary, it jumped into the instrumented function but exit normally before printf("stubbed jmp").
Could anyone give me a hint please?

**Comment by ba0f3** [comment]
I think you should use `pt.hook(pt.entry, addr)` instead of hard-coded address

**Comment by Ver0n1ca** [comment]
> I think you should use `pt.hook(pt.entry, addr)` instead of hard-coded address

My PIE is off so I guess hard-coded address is OK?

**Comment by Ver0n1ca** [comment]
I used a syscall instead of a printf solved the problem :D

**Comment by ba0f3** [comment]
cuz you hooked-it-away :)) you must save the original ptr for later use

**Comment by lunixbochs** [comment]
The C stdlib in patchkit is for CGC right now. printf didn't work because it tried calling the CGC `transmit` syscall. https://github.com/lunixbochs/patchkit/issues/7

**Comment by Ver0n1ca** [comment]
Oh I see, thank you guys!
